import logging

__version__ = "2.2.0"
logging.info(f"### Loading: ComfyUI_IR_Lite (v{__version__})")

from .Pac.IRL_adjustments import (
    ADJUSTMENTS_NODE_CLASS_MAPPINGS,
    ADJUSTMENTS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .Pac.IRL_filters import (
    FILTERS_NODE_CLASS_MAPPINGS,
    FILTERS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .Pac.IRL_composite import (
    COMPOSITE_NODE_CLASS_MAPPINGS,
    COMPOSITE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .Pac.IRL_transform import (
    TRANSFORM_NODE_CLASS_MAPPINGS,
    TRANSFORM_NODE_DISPLAY_NAME_MAPPINGS,
)
from .Pac.IRL_noise import (
    NOISE_NODE_CLASS_MAPPINGS,
    NOISE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .Pac.IRL_analysis import (
    ANALYSIS_NODE_CLASS_MAPPINGS,
    ANALYSIS_NODE_DISPLAY_NAME_MAPPINGS,
)




# 클래스 매핑 합치기
NODE_CLASS_MAPPINGS = {
    **ADJUSTMENTS_NODE_CLASS_MAPPINGS,
    **FILTERS_NODE_CLASS_MAPPINGS,
    **COMPOSITE_NODE_CLASS_MAPPINGS,
    **TRANSFORM_NODE_CLASS_MAPPINGS,
    **NOISE_NODE_CLASS_MAPPINGS,
    **ANALYSIS_NODE_CLASS_MAPPINGS,
}


# 디스플레이 네임 매핑 합치기
NODE_DISPLAY_NAME_MAPPINGS = {
    **ADJUSTMENTS_NODE_DISPLAY_NAME_MAPPINGS,
    **FILTERS_NODE_DISPLAY_NAME_MAPPINGS,
    **COMPOSITE_NODE_DISPLAY_NAME_MAPPINGS,
    **TRANSFORM_NODE_DISPLAY_NAME_MAPPINGS,
    **NOISE_NODE_DISPLAY_NAME_MAPPINGS,
    **ANALYSIS_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "__version__",
]

